### ISSUE TITLE
Support vue3?

### ISSUE THREAD

**Issue by Wxh16144** [xxholly32/rollup-plugin-vue-jsx#1]

**Comment by BuptStEve** [comment]
Yeah...

https://github.com/xxholly32/rollup-plugin-vue-jsx/blob/c654d72a5372ab168d91075f36f1f123e85cd2bd/src/vue-jsx-compat.ts#L3

**Comment by xxholly32** [comment]
I haven't tried it. Is cant work?

**Comment by Wxh16144** [comment]
Instead of trying again, instead of using `rollup`, I used [vite.build](https://vitejs.dev/config/#build-options) to build my package.

**Comment by Wxh16144** [comment]
> I haven't tried it. Is cant work?

should be able to
